<?php

namespace dzonibg\bladecomponents;
use Illuminate\Support\ServiceProvider;

class BladeComponents extends ServiceProvider {

    public function boot() {
        $this->loadViewsFrom(__DIR__.'/resources/views', 'bladecomponents');
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
